//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;


namespace Retailers.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.SALES = new HashSet<SALE>();
        }
    
        public int Customer_ID { get; set; }
        public string CUSTOMER_NM { get; set; }
    
        public virtual ICollection<SALE> SALES { get; set; }
    }
}
