//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;


namespace Retailers.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int Transaction_Id { get; set; }
        public System.DateTime Transaction_date { get; set; }
        public int Customer_ID { get; set; }
        public decimal Transaction_value { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
